const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PROJECT_NAME = "."; // Cria na raiz
const BACKEND_DIR = path.join(PROJECT_NAME, 'backend');
const FRONTEND_DIR = path.join(PROJECT_NAME, 'frontend');

console.log('>>> GERANDO GEMINI CLONE FULLSTACK... <<<');

const backendFiles = {
  'package.json': JSON.stringify({
      name: "ai-backend", version: "1.0.0", main: "server.js",
          scripts: { "start": "node server.js" },
              dependencies: { "bcryptjs": "^2.4.3", "cors": "^2.8.5", "dotenv": "^16.0.3", "express": "^4.18.2", "jsonwebtoken": "^9.0.0", "mongoose": "^7.0.3", "openai": "^4.28.0", "puppeteer": "^22.0.0" }
                }, null, 2),

                  'models/User.js': `const mongoose = require('mongoose');
                  const UserSchema = new mongoose.Schema({
                    username: { type: String, required: true, unique: true },
                      password: { type: String, required: true },
                        role: { type: String, enum: ['user', 'admin'], default: 'user' },
                          personal_api_key: { type: String, default: '' },
                            usage: { requests: { type: Number, default: 0 } },
                              createdAt: { type: Date, default: Date.now }
                              }); module.exports = mongoose.model('User', UserSchema);`,

                                'models/Chat.js': `const mongoose = require('mongoose');
                                const ChatSchema = new mongoose.Schema({
                                  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
                                    title: { type: String, default: 'Novo Chat' },
                                      messages: [{ role: { type: String }, content: { type: String }, timestamp: { type: Date, default: Date.now } }]
                                      }); module.exports = mongoose.model('Chat', ChatSchema);`,

                                        'server.js': `
                                        require('dotenv').config();
                                        const express = require('express');
                                        const mongoose = require('mongoose');
                                        const cors = require('cors');
                                        const jwt = require('jsonwebtoken');
                                        const bcrypt = require('bcryptjs');
                                        const OpenAI = require('openai');
                                        const { exec } = require('child_process');
                                        const puppeteer = require('puppeteer');
                                        const User = require('./models/User');
                                        const Chat = require('./models/Chat');

                                        const app = express();
                                        app.use(cors());
                                        app.use(express.json());

                                        const PORT = process.env.PORT || 3000;
                                        const JWT_SECRET = process.env.JWT_SECRET || 'secret';
                                        const GLOBAL_API_KEY = process.env.GLOBAL_API_KEY;
                                        const DEFAULT_MODEL = "google/gemini-2.0-flash-exp:free";

                                        // Seed Admin
                                        const createInitialAdmin = async () => {
                                          try {
                                              if (!await User.findOne({ username: 'admin' })) {
                                                    const hash = await bcrypt.hash('@admin2306#', 10);
                                                          await User.create({ username: 'admin', password: hash, role: 'admin' });
                                                                console.log('>>> ADMIN CRIADO: admin / @admin2306# <<<');
                                                                    }
                                                                      } catch (e) { console.error(e); }
                                                                      };

                                                                      mongoose.connect(process.env.MONGODB_URI)
                                                                        .then(() => { console.log('DB Conectado'); createInitialAdmin(); })
                                                                          .catch(err => console.error(err));

                                                                          const auth = async (req, res, next) => {
                                                                            const token = req.header('Authorization')?.replace('Bearer ', '');
                                                                              if (!token) return res.status(401).send('Negado');
                                                                                try {
                                                                                    const verified = jwt.verify(token, JWT_SECRET);
                                                                                        req.user = await User.findById(verified.id);
                                                                                            next();
                                                                                              } catch (err) { res.status(400).send('Token invalido'); }
                                                                                              };

                                                                                              // Tools
                                                                                              const runSafeTerminal = (cmd) => new Promise(res => {
                                                                                                const allowed = ['ls', 'pwd', 'cat', 'grep', 'whoami', 'date', 'echo', 'ping', 'curl', 'ps', 'node -v', 'git status'];
                                                                                                  if (cmd.includes('>') || cmd.includes('|') || !allowed.includes(cmd.split(' ')[0])) return res("COMANDO PROIBIDO");
                                                                                                    exec(cmd, { timeout: 5000 }, (e, out, err) => res(e ? "Erro: "+e.message : out || err));
                                                                                                    });

                                                                                                    const analyzeNetwork = async (url) => {
                                                                                                      try {
                                                                                                          const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
                                                                                                              const page = await browser.newPage();
                                                                                                                  const reqs = [];
                                                                                                                      page.on('request', r => reqs.push({ url: r.url(), method: r.method() }));
                                                                                                                          await page.goto(url, { waitUntil: 'networkidle0', timeout: 10000 });
                                                                                                                              await browser.close();
                                                                                                                                  return JSON.stringify(reqs.slice(0, 30));
                                                                                                                                    } catch (e) { return "Erro: " + e.message; }
                                                                                                                                    };

                                                                                                                                    // Routes
                                                                                                                                    app.post('/api/chat', auth, async (req, res) => {
                                                                                                                                      const { messages, model, systemPrompt, toolsEnabled } = req.body;
                                                                                                                                        const apiKey = req.user.personal_api_key || GLOBAL_API_KEY;
                                                                                                                                          const openai = new OpenAI({ baseURL: "https://openrouter.ai/api/v1", apiKey });
                                                                                                                                            
                                                                                                                                              await User.findByIdAndUpdate(req.user._id, { $inc: { "usage.requests": 1 } });
                                                                                                                                                
                                                                                                                                                  // Salvar Chat (Opcional - Logica basica)
                                                                                                                                                    let chat = await Chat.findOne({ userId: req.user._id }).sort({_id:-1});
                                                                                                                                                      if(!chat) chat = await Chat.create({ userId: req.user._id, messages: [] });
                                                                                                                                                        // Aqui voce pode expandir para salvar historico real no banco

                                                                                                                                                          const tools = [
                                                                                                                                                              { type: "function", function: { name: "terminal", description: "Read-only terminal", parameters: { type: "object", properties: { cmd: { type: "string" } } } } },
                                                                                                                                                                  { type: "function", function: { name: "network_analyzer", description: "Analyze network", parameters: { type: "object", properties: { url: { type: "string" } } } } }
                                                                                                                                                                    ];

                                                                                                                                                                      try {
                                                                                                                                                                          const allMsgs = systemPrompt ? [{role:"system", content:systemPrompt}, ...messages] : messages;
                                                                                                                                                                              const resp = await openai.chat.completions.create({ model: model || DEFAULT_MODEL, messages: allMsgs, tools: toolsEnabled ? tools : undefined });
                                                                                                                                                                                  const msg = resp.choices[0].message;

                                                                                                                                                                                      if (msg.tool_calls) {
                                                                                                                                                                                            const tool = msg.tool_calls[0];
                                                                                                                                                                                                  const args = JSON.parse(tool.function.arguments);
                                                                                                                                                                                                        const result = tool.function.name === 'terminal' ? await runSafeTerminal(args.cmd) : await analyzeNetwork(args.url);
                                                                                                                                                                                                              const final = await openai.chat.completions.create({ model: model || DEFAULT_MODEL, messages: [...allMsgs, msg, { role: "tool", tool_call_id: tool.id, content: result }] });
                                                                                                                                                                                                                    return res.json(final.choices[0].message);
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                            res.json(msg);
                                                                                                                                                                                                                              } catch (e) { res.status(500).json({ error: e.message }); }
                                                                                                                                                                                                                              });

                                                                                                                                                                                                                              app.post('/api/swarm', auth, async (req, res) => {
                                                                                                                                                                                                                                const { task, model } = req.body;
                                                                                                                                                                                                                                  const apiKey = req.user.personal_api_key || GLOBAL_API_KEY;
                                                                                                                                                                                                                                    const targetModel = model || DEFAULT_MODEL;
                                                                                                                                                                                                                                      const openai = new OpenAI({ baseURL: "https://openrouter.ai/api/v1", apiKey });

                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                            const plan = await openai.chat.completions.create({ model: targetModel, messages: [{ role: "system", content: "Return JSON array of subtasks." }, { role: "user", content: task }] });
                                                                                                                                                                                                                                                let subtasks = [task];
                                                                                                                                                                                                                                                    try { subtasks = JSON.parse(plan.choices[0].message.content.replace(/\\\`\\\`\\\`json|\\\`\\\`\\\`/g, '')); } catch(e){}
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            const results = await Promise.all(subtasks.slice(0, 30).map(t => 
                                                                                                                                                                                                                                                                  openai.chat.completions.create({ model: targetModel, messages: [{ role: "user", content: JSON.stringify(t) }] })
                                                                                                                                                                                                                                                                        .then(r => r.choices[0].message.content).catch(e => "Error")
                                                                                                                                                                                                                                                                            ));

                                                                                                                                                                                                                                                                                const summary = await openai.chat.completions.create({ model: targetModel, messages: [{ role: "system", content: "Summarize." }, { role: "user", content: JSON.stringify(results) }] });
                                                                                                                                                                                                                                                                                    res.json(summary.choices[0].message);
                                                                                                                                                                                                                                                                                      } catch (e) { res.status(500).json({ error: e.message }); }
                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                      app.post('/api/login', async (req, res) => {
                                                                                                                                                                                                                                                                                        const { username, password } = req.body;
                                                                                                                                                                                                                                                                                          const user = await User.findOne({ username });
                                                                                                                                                                                                                                                                                            if (!user || !await bcrypt.compare(password, user.password)) return res.status(400).send('Invalid');
                                                                                                                                                                                                                                                                                              res.json({ token: jwt.sign({ id: user._id }, JWT_SECRET), role: user.role, username: user.username });
                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                              app.get('/api/admin/data', auth, async (req, res) => {
                                                                                                                                                                                                                                                                                                const users = await User.find({}, '-password');
                                                                                                                                                                                                                                                                                                  res.json({ users, chats: [] }); // Simplificado para demo
                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                  app.listen(PORT, () => console.log('Server running'));
                                                                                                                                                                                                                                                                                                  `
                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                  const frontendFiles = {
                                                                                                                                                                                                                                                                                                    'package.json': JSON.stringify({ name: "ai-frontend", type: "module", scripts: { "dev": "vite", "build": "vite build" }, dependencies: { "axios": "^1.6.0", "lucide-react": "^0.292.0", "react": "^18.2.0", "react-dom": "^18.2.0", "react-router-dom": "^6.18.0" }, devDependencies: { "@vitejs/plugin-react": "^4.2.0", "autoprefixer": "^10.4.16", "postcss": "^8.4.31", "tailwindcss": "^3.3.5", "vite": "^5.0.0" } }, null, 2),
                                                                                                                                                                                                                                                                                                      'vite.config.js': `import { defineConfig } from 'vite'; import react from '@vitejs/plugin-react'; export default defineConfig({ plugins: [react()] });`,
                                                                                                                                                                                                                                                                                                        'postcss.config.js': `export default { plugins: { tailwindcss: {}, autoprefixer: {}, }, }`,
                                                                                                                                                                                                                                                                                                          'tailwind.config.js': `export default { content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"], theme: { extend: {}, }, plugins: [], }`,
                                                                                                                                                                                                                                                                                                            'index.html': `<!doctype html><html lang="en"><head><meta charset="UTF-8" /><title>AI Platform</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>`,
                                                                                                                                                                                                                                                                                                              'src/main.jsx': `import React from 'react'; import ReactDOM from 'react-dom/client'; import App from './App.jsx'; import './index.css'; ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);`,
                                                                                                                                                                                                                                                                                                                'src/index.css': `@tailwind base; @tailwind components; @tailwind utilities;`,
                                                                                                                                                                                                                                                                                                                  'src/App.jsx': `
                                                                                                                                                                                                                                                                                                                  import React, { useState, useEffect } from 'react';
                                                                                                                                                                                                                                                                                                                  import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
                                                                                                                                                                                                                                                                                                                  import axios from 'axios';
                                                                                                                                                                                                                                                                                                                  import { Cpu, Settings, LogOut } from 'lucide-react';

                                                                                                                                                                                                                                                                                                                  const API_URL = import.meta.env.VITE_API_URL;

                                                                                                                                                                                                                                                                                                                  function Login({ setUser }) {
                                                                                                                                                                                                                                                                                                                    const [u, setU] = useState(''); const [p, setP] = useState('');
                                                                                                                                                                                                                                                                                                                      const login = async (e) => {
                                                                                                                                                                                                                                                                                                                          e.preventDefault();
                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                    const res = await axios.post(API_URL + '/login', { username: u, password: p });
                                                                                                                                                                                                                                                                                                                                          localStorage.setItem('user', JSON.stringify(res.data)); setUser(res.data);
                                                                                                                                                                                                                                                                                                                                              } catch { alert('Erro login'); }
                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                      <div className="h-screen flex items-center justify-center bg-gray-900 text-white">
                                                                                                                                                                                                                                                                                                                                                            <form onSubmit={login} className="bg-gray-800 p-8 rounded w-80">
                                                                                                                                                                                                                                                                                                                                                                    <h2 className="mb-4 font-bold">Login System</h2>
                                                                                                                                                                                                                                                                                                                                                                            <input className="w-full mb-2 p-2 bg-gray-700 rounded" placeholder="User" onChange={e=>setU(e.target.value)}/>
                                                                                                                                                                                                                                                                                                                                                                                    <input className="w-full mb-4 p-2 bg-gray-700 rounded" type="password" placeholder="Pass" onChange={e=>setP(e.target.value)}/>
                                                                                                                                                                                                                                                                                                                                                                                            <button className="w-full bg-blue-600 p-2 rounded">Entrar</button>
                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        function Chat({ user }) {
                                                                                                                                                                                                                                                                                                                                                                                                          const [msgs, setMsgs] = useState([]); const [inpt, setInpt] = useState('');
                                                                                                                                                                                                                                                                                                                                                                                                            const [mode, setMode] = useState('chat'); const [model, setModel] = useState("google/gemini-2.0-flash-exp:free");
                                                                                                                                                                                                                                                                                                                                                                                                              const send = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                  if(!inpt) return;
                                                                                                                                                                                                                                                                                                                                                                                                                      const newM = [...msgs, {role:'user', content:inpt}]; setMsgs(newM); setInpt('');
                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                const ep = mode === 'swarm' ? '/swarm' : '/chat';
                                                                                                                                                                                                                                                                                                                                                                                                                                      const pl = mode === 'swarm' ? {task:inpt, model} : {messages:newM, model, toolsEnabled:true};
                                                                                                                                                                                                                                                                                                                                                                                                                                            const res = await axios.post(API_URL+ep, pl, {headers:{Authorization:'Bearer '+user.token}});
                                                                                                                                                                                                                                                                                                                                                                                                                                                  setMsgs([...newM, mode==='swarm'?{role:'assistant', content:'[SWARM]:\\n'+res.data.content}:res.data]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch(e) { setMsgs([...newM, {role:'assistant', content:'Error: '+e.message}]); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex h-screen bg-gray-900 text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="w-64 bg-gray-800 p-4 border-r border-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h1 className="font-bold text-blue-400 mb-6">AI System</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={()=>setMode('chat')} className="block w-full text-left p-2 hover:bg-gray-700 rounded">Chat</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={()=>setMode('swarm')} className="block w-full text-left p-2 hover:bg-gray-700 rounded text-purple-400">Swarm (30x)</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select className="w-full bg-gray-900 p-2 rounded border border-gray-600 text-xs" onChange={e=>setModel(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="google/gemini-2.0-flash-exp:free">Gemini 2.0 Free</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="meta-llama/llama-3-8b-instruct:free">Llama 3 Free</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {user.role==='admin' && <div className="mt-4 text-yellow-500 text-xs">Admin Mode Active</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex-1 flex flex-col p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex-1 overflow-y-auto mb-4 space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {msgs.map((m,i)=><div key={i} className={\`p-3 rounded max-w-3xl \${m.role==='user'?'bg-blue-900 ml-auto':'bg-gray-800'}\`}><pre className="whitespace-pre-wrap text-sm">{m.content}</pre></div>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input className="flex-1 bg-gray-800 p-2 rounded border border-gray-600" value={inpt} onChange={e=>setInpt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={send} className="bg-blue-600 px-4 rounded">Send</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default function App() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [user, setUser] = useState(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              useEffect(()=>{ const u = localStorage.getItem('user'); if(u) setUser(JSON.parse(u)); },[]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <BrowserRouter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Route path="/login" element={<Login setUser={setUser} />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route path="/" element={user ? <Chat user={user}/> : <Navigate to="/login" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </BrowserRouter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function write(fp, ct) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const p = path.join(PROJECT_NAME, fp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if(!fs.existsSync(path.dirname(p))) fs.mkdirSync(path.dirname(p), {recursive:true});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fs.writeFileSync(p, ct.trim());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('Criado: '+fp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Object.keys(backendFiles).forEach(k => write('backend/'+k, backendFiles[k]));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Object.keys(frontendFiles).forEach(k => write('frontend/'+k, frontendFiles[k]));