import React, { useState, useEffect } from 'react';
                                                                                                                                                                                                                                                                                                                  import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
                                                                                                                                                                                                                                                                                                                  import axios from 'axios';
                                                                                                                                                                                                                                                                                                                  import { Cpu, Settings, LogOut } from 'lucide-react';

                                                                                                                                                                                                                                                                                                                  const API_URL = import.meta.env.VITE_API_URL;

                                                                                                                                                                                                                                                                                                                  function Login({ setUser }) {
                                                                                                                                                                                                                                                                                                                    const [u, setU] = useState(''); const [p, setP] = useState('');
                                                                                                                                                                                                                                                                                                                      const login = async (e) => {
                                                                                                                                                                                                                                                                                                                          e.preventDefault();
                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                    const res = await axios.post(API_URL + '/login', { username: u, password: p });
                                                                                                                                                                                                                                                                                                                                          localStorage.setItem('user', JSON.stringify(res.data)); setUser(res.data);
                                                                                                                                                                                                                                                                                                                                              } catch { alert('Erro login'); }
                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                      <div className="h-screen flex items-center justify-center bg-gray-900 text-white">
                                                                                                                                                                                                                                                                                                                                                            <form onSubmit={login} className="bg-gray-800 p-8 rounded w-80">
                                                                                                                                                                                                                                                                                                                                                                    <h2 className="mb-4 font-bold">Login System</h2>
                                                                                                                                                                                                                                                                                                                                                                            <input className="w-full mb-2 p-2 bg-gray-700 rounded" placeholder="User" onChange={e=>setU(e.target.value)}/>
                                                                                                                                                                                                                                                                                                                                                                                    <input className="w-full mb-4 p-2 bg-gray-700 rounded" type="password" placeholder="Pass" onChange={e=>setP(e.target.value)}/>
                                                                                                                                                                                                                                                                                                                                                                                            <button className="w-full bg-blue-600 p-2 rounded">Entrar</button>
                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        function Chat({ user }) {
                                                                                                                                                                                                                                                                                                                                                                                                          const [msgs, setMsgs] = useState([]); const [inpt, setInpt] = useState('');
                                                                                                                                                                                                                                                                                                                                                                                                            const [mode, setMode] = useState('chat'); const [model, setModel] = useState("google/gemini-2.0-flash-exp:free");
                                                                                                                                                                                                                                                                                                                                                                                                              const send = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                  if(!inpt) return;
                                                                                                                                                                                                                                                                                                                                                                                                                      const newM = [...msgs, {role:'user', content:inpt}]; setMsgs(newM); setInpt('');
                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                const ep = mode === 'swarm' ? '/swarm' : '/chat';
                                                                                                                                                                                                                                                                                                                                                                                                                                      const pl = mode === 'swarm' ? {task:inpt, model} : {messages:newM, model, toolsEnabled:true};
                                                                                                                                                                                                                                                                                                                                                                                                                                            const res = await axios.post(API_URL+ep, pl, {headers:{Authorization:'Bearer '+user.token}});
                                                                                                                                                                                                                                                                                                                                                                                                                                                  setMsgs([...newM, mode==='swarm'?{role:'assistant', content:'[SWARM]:\n'+res.data.content}:res.data]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch(e) { setMsgs([...newM, {role:'assistant', content:'Error: '+e.message}]); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex h-screen bg-gray-900 text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="w-64 bg-gray-800 p-4 border-r border-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h1 className="font-bold text-blue-400 mb-6">AI System</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={()=>setMode('chat')} className="block w-full text-left p-2 hover:bg-gray-700 rounded">Chat</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={()=>setMode('swarm')} className="block w-full text-left p-2 hover:bg-gray-700 rounded text-purple-400">Swarm (30x)</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select className="w-full bg-gray-900 p-2 rounded border border-gray-600 text-xs" onChange={e=>setModel(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="google/gemini-2.0-flash-exp:free">Gemini 2.0 Free</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="meta-llama/llama-3-8b-instruct:free">Llama 3 Free</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {user.role==='admin' && <div className="mt-4 text-yellow-500 text-xs">Admin Mode Active</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex-1 flex flex-col p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex-1 overflow-y-auto mb-4 space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {msgs.map((m,i)=><div key={i} className={`p-3 rounded max-w-3xl ${m.role==='user'?'bg-blue-900 ml-auto':'bg-gray-800'}`}><pre className="whitespace-pre-wrap text-sm">{m.content}</pre></div>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input className="flex-1 bg-gray-800 p-2 rounded border border-gray-600" value={inpt} onChange={e=>setInpt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={send} className="bg-blue-600 px-4 rounded">Send</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default function App() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [user, setUser] = useState(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              useEffect(()=>{ const u = localStorage.getItem('user'); if(u) setUser(JSON.parse(u)); },[]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <BrowserRouter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Route path="/login" element={<Login setUser={setUser} />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route path="/" element={user ? <Chat user={user}/> : <Navigate to="/login" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </BrowserRouter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }